name: Bug report
description: 'Report a bug.'
title: "[Bug] <Short description>"
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
      Before you fill out this bug report, please read **[the Reynard Browser FAQ](https://github.com/minh-ton/reynard-browser/issues/130) and [search in GitHub Issues](https://github.com/minh-ton/reynard-browser/issues)** for the bug you are experiencing.

- type: checkboxes
  attributes:
    label: Before continuing, please confirm the following
    options:
      - label: I have read the FAQ and searched for my issue.
  validations:
    required: true

- type: textarea
  id: version
  attributes:
    label: Describe the bug
    description: |
      A clear description of what the bug is and how you discovered it. Try to be as specific as possible and include any relevant details that could help the developer understand the issue.

      Please note that "Doesn't work" is not a helpful description. Instead, describe what you expected to happen and what actually happened.
      For example, instead of saying "Cannot add bookmarks please fix", you could say "I visited example.com and tried to add it to bookmarks, but I can't find the option to do so in the address bar menu. I expected to see an 'Add to Bookmarks' option there."
  validations:
    required: true

- type: textarea
  attributes:
    label: Crash log and/or screenshots
    description: |
      If a crash happened, please upload the crash log in iOS settings -> Privacy Security -> Analytics Improvements -> Analytics Data -> Search for **Reynard** or **Reynard Helper**. 
      
      **Do not copy and paste.** Instead, export the crash log and change its extension from .ips to .txt and upload it. If you are certain no crash report is produced, type "No crash report is produced".
  validations:
    required: false

- type: textarea
  attributes:
    label: Steps to reproduce
    description: Please include consistent instructions for reproducing the bug.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Platform
    description: |
      Examples:
        - **iOS version**: 26.1
        - **Device model**: iPhone 13 mini
        - **Sideloading method**: SideStore
        - **Reynard Browser version**: 0.4.0
    value: |
        - iOS version:
        - Device model: 
        - Sideloading method:
        - Reynard Browser version: 
  validations:
    required: true

- type: checkboxes
  attributes:
    label: Verify steps
    options:
      - label: I have the latest version of Reynard Browser.
      - label: I use the official build of Reynard Browser from GitHub releases.
      - label: I have read the installation instructions and have followed all of the steps to install Reynard Browser correctly.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      If you have any other information that you think is relevant to the bug, please include it here. This could be anything from additional screenshots, to a more detailed description of the issue, to potential workarounds you've found.
  validations:
    required: false
