name: Feature request
description: 'Ask for new features or improvements.'
title: "[Feature Request] <Short description>"
labels: [enhancement]
body:
- type: markdown
  attributes:
    value: |
      Before you fill out this feature request, please **[search in GitHub Issues](https://github.com/minh-ton/reynard-browser/issues)** to see if your feature has already been requested.

- type: checkboxes
  attributes:
    label: Before continuing, please confirm the following
    options:
      - label: This feature request has not been made before.
  validations:
    required: true

- type: textarea
  attributes:
    label: Describe the feature request or improvement you want to see
    description: |
      A clear and concise description of the feature request or improvement you want to see in Reynard Browser. 
      
      Try to be as specific as possible and include any relevant details that could help the developer understand your request. You can also include screenshots or mockups if you have any ideas on how the feature should look like.
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      If you have any other information that you think is relevant to the feature request, please include it here.
  validations:
    required: false
